---
apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  name: triton-server
spec:
  lookupPolicy:
    local: true
  tags:
  - name: mobilenet
  - name: latest
    from:
      kind: ImageStreamTag
      name: triton-server:mobilenet
    referencePolicy:
      type: Local
