---
kind: BuildConfig
apiVersion: build.openshift.io/v1
metadata:
  name: triton-server-git
  annotations:
    argocd.argoproj.io/sync-wave: "2"
  labels:
    build: triton-server
spec:
  runPolicy: Serial
  source:
    git:
      uri: https://github.com/codekow/s2i-triton.git
      ref: dev
    contextDir: models
  strategy:
    sourceStrategy:
      from:
        kind: ImageStreamTag
        name: triton-builder:latest
  output:
    to:
      kind: ImageStreamTag
      name: triton-server:latest
  triggers:
    - type: ConfigChange
    - type: ImageChange
      imageChange:
        from:
          kind: ImageStreamTag
          name: triton-builder:latest
