---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

labels:
- includeSelectors: true
  pairs:
    app: triton-server
    app.kubernetes.io/component: triton-server
    app.kubernetes.io/instance: triton-server
    app.kubernetes.io/part-of: triton-server

resources:
- deployment.yaml
- imagestream.yaml
- route.yaml
- service.yaml
