---
apiVersion: v1
kind: Namespace
metadata:
  name: demo-triton
  annotations:
    openshift.io/display-name: "Demo - Triton"
    openshift.io/description: "A model serving example"
    argocd.argoproj.io/sync-wave: "0"
