---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: demo-triton

resources:
- ../../base
- namespace.yaml

components:
- ../../components/docker-build
- ../../components/source-build

patches:
- path: imagestream.yaml
